### ISSUE TITLE
[FEATURE] Comprehend Detect Key phrases 

### ISSUE THREAD

**Issue by OElesin** [aws-samples/aws-athena-udfs-textanalytics#3]
**Is your feature request related to a problem? If yes, please describe.**
Detecting key phrases would be super valuable for analytics especially when diving deep into sentiments. This will help understand the keywords around specific sentiments.

**Describe the solution you'd like**
Add the function `detect_key_phrases()` to the text analytics UDF.

**Comment by rstrahan** [comment]
@OElesin your wish is my command :)
I added detect_key_phrases, and detect_key_phrases_all functions - see [README - Detect Key Phrases](https://github.com/aws-samples/aws-athena-udfs-textanalytics/blob/main/athena-udfs-textanalytics/README.md#detect-key-phrases), along with code refactoring to use AWS Java SDK v2. Published to SAR as [TextAnalyticsUDFHandler — version 0.3.0](https://console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:912625584728:applications/TextAnalyticsUDFHandler)
Hope it's useful for you..

**Comment by OElesin** [comment]
Thanks redeployed and tested.
